### ISSUE TITLE
This still works?

### ISSUE THREAD

**Issue by danawoodman** [dafn/svelte-typescript-parcel#1]
I'm trying to get Svelte + TS +Parcel working and I found your project but I am getting an error in my `index.ts` file where TS cannot import the Svelte file:

![](https://cl.ly/2deaea96a109/Screen%20Shot%202019-09-28%20at%2011.58.48%20AM.png)

I'm confused how you were able to import `.svelte` into your Typescript files and have it actually compile?

**EDIT**: I added the `types` folder and that fixed the one issue but I still get no output when compiling and (at least VSCode) is showing an error in the `.svelte` file:

![](https://cl.ly/f408155fd637/Screen%20Shot%202019-09-28%20at%2012.01.40%20PM.png)

**Comment by dafn** [comment]
Sorry for the late answer.

As svelte does not officially support typescript the provided intellisense does not understand other dialects than ES. It should still compile fine though.

I just updateed the project. It now uses a different, more flexible preprocessor. It might also solve your intellisense problems.

Btw: The svelte.d.ts file is vital for the ts compiler. if it is not provided the comiler will not recognise *.svelte files
